  version: '3.8'

  volumes:
    pg_data:

  services:
    db:
      image: postgres:13-alpine
      container_name: db_postgre
      env_file: .env
      volumes:
        - pg_data:/var/lib/postgresql/data

    backend:
      image: lordrie/backend
      container_name: backend_app
      command: ["/app/docker/app.sh"]
      env_file: .env
      depends_on:
        - db

    nginx:
      image: nginx:1.19.3
      env_file: .env
      container_name: nginx
      volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
      - 8000:80
      depends_on:
        - backend

    # redis:
    #   image: redis:7
    #   container_name: redis
