version: '3.8'

volumes:
  pg_data:

services:
  db:
    image: postgres:13-alpine
    container_name: db_postgre
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: backend_app
    command: ["/app/docker/app.sh"]
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - db

  nginx:
      image: nginx:1.19.3
      env_file: .env
      container_name: nginx
      ports:
      - 8000:80
      depends_on:
        - backend
