  version: '3.8'

  volumes:
    pg_data:

  services:
    db:
      image: postgres:13-alpine
      container_name: db_postgre
      ports:
        - 5432:5432
      env_file: .env
      volumes:
        - pg_data:/var/lib/postgresql/data

    backend:
      build: ../.
      container_name: backend_app
      env_file: .env
      depends_on:
        - db

    frontend:
      build:
        context: ../frontend
        dockerfile: Dockerfile
      volumes:
        - ../frontend/:/app/build
      depends_on:
        - backend

    nginx:
        image: nginx:1.19.3
        env_file: .env
        container_name: nginx
        volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
        - .././frontend/build:/usr/share/nginx/html/
        ports:
        - 8000:80
        depends_on:
          - backend
          - frontend

    redis:
        image: redis:7
        container_name: redis
