name: HRSpace
on:
  push:
    # Отслеживаем изменения только в ветке docker
    branches:
      - docker
# Перечень задач
jobs:
  # Единственная задача — склонировать код
  # и вывести в консоль дерево файлов
  checkout-and-print-tree:
    runs-on: ubuntu-latest
    steps:
      # На GitHub Actions есть готовые описания шагов,
      # их можно использовать в своих workflow.
      # Применим готовое описание шага для получения исходного кода
      - name: Чек  # Имя шага задаём сами
        uses: actions/checkout@v3  # Берём готовое решение из библиотеки GitHub Actions
      # Выполняем команду tree в текущей директории
      - name: Print project tree
        run: tree .
